# Generated by CmdBridge
# Target OS: windows
# Target Shell: powershell

# Setup environment
$env: MY_DIR="build"

Write-Output "Creating build
New-Item -ItemType Directory $MY_DIR

# CmdBridge Notice
# Unsupported block preserved below.
if [ -d $MY_DIR ]; then
# End preserved block
    Write-Output "Directory created."
# CmdBridge Notice
# Unsupported block preserved below.
fi
# End preserved block

Copy-Item config.json $MY_DIR/
Remove-Item temp/

# Done
