find|searches files/directories
.|current directory
-name|match by filename
ls|lists directory contents
-l|use a long listing format
-a|do not ignore entries starting with .
mkdir|make directories
rm|remove files or directories
-r|remove directories and their contents recursively
-rf|remove directories and contents recursively, without prompting
-Force|force the operation
-Recurse|perform the operation recursively
Get-ChildItem|gets the items and child items in one or more specified locations
-Filter|specifies a filter to qualify the Path parameter
tasklist|displays a list of currently running processes
ps|report a snapshot of the current processes
aux|show all processes for all users
dir|displays a list of files and subdirectories in a directory
